### ISSUE TITLE
Merge values rather than overwriting

### ISSUE THREAD

**Issue by tonsV2** [tonsV2/helmstack#5]
In https://github.com/tonsV2/helmstack/blob/master/helmstack.py#L108 values should be merged rather than overwritten.

helmstack.yaml
```
releases:
  - name: postgres
    namespace: event-streaming-platform
    chart: chart/postgres
    values:
      - local-values/postgres.yaml

```
env.dev.yaml
```
releases:
  postgres:
    values:
      - other/values.yaml
```
Should result in...
```
releases:
  - name: postgres
    namespace: event-streaming-platform
    chart: chart/postgres
    values:
      - local-values/postgres.yaml
      - other/values.yaml

```
